version: '3.8'
services:
  db:
    image: mysql:8.0
    command: [
        "--host_cache_size=0",          # Substitui --skip-host-cache
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
    ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: [
          "CMD-SHELL",
          "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD --protocol=tcp"
      ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
    command: >
      sh -c "
        until mysqladmin ping -hdb --silent; do
          echo '→ aguardando db…'; sleep 2;
        done &&
        echo '→ banco OK, aplicando migrations' &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        echo '→ iniciando servidor' &&
        gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
