version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      # serão preenchidas de .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
    command: >
      sh -c "
        until mysqladmin ping -hdb --silent; do
          echo '→ aguardando db…'; sleep 2;
        done &&
        echo '→ banco OK, aplicando migrations' &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        echo '→ iniciando servidor' &&
        gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
