# Generated by Django 4.2.21 on 2025-05-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_limited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
